plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/ubuntu/goldenhome-mirror/69c6f09f7ba84ab92d40590e--goldenhome-cabinetry.netlify.app"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]